### PR TITLE
Changed Crew Picture

### PR DESCRIPTION
**Pull request by offlinemark**
Sorry about that previous pull request. Fresh repo this time, added the new crew picture, as well as some extra padding around the text and icons to make things a little less cramped looking, imo.

### CODE REVIEW

**Comment by pranav** [comment]
This version is now live. http://crew.ccs.neu.edu

**Comment by offlinemark** [comment]
Content needs to seriously be cleaned up.

**Comment by pranav** [comment]
Well, get on it!

## 

Pranav Gandhi
Sent with Sparrow (http://www.sparrowmailapp.com/?sig)

**Comment by offlinemark** [comment]
Just pointing it out! Will take a look when I'm back near a computer

**Pull request merged**
