### PR TITLE
CREW Website Draft

### PR DESCRIPTION
**Pull request by alekhinen**
This is what I made on a train ride. It's still pretty rough, but the
general structure of the information is there. The content really needs
to get fleshed out. The panorama seen in the page is placeholder for
now.

### CODE REVIEW

**Comment by alekhinen** [comment]
Here's a screenshot for anyone interested. 
crew_screenshot

**Comment by pranav** [comment]
I _really_ like this

**Comment by pranav** [comment]
@ali what do you think?

**Comment by ali** [comment]
Looks good! Really liking the large text, and you did a good job with the site structure.

We'll talk about this at the web team meeting :+1:

**Pull request merged**
