### PR TITLE
Minor CSS Changes

### PR DESCRIPTION
**Pull request by nguyent**
See commit message.

### CODE REVIEW

**Comment by wylieconlon** [comment]
I don't think your commit actually changes any CSS...?

**Comment by nguyent** [comment]
bah, I checked out the original repo and not my fork so I had to re-commit and forgot the CSS file.

**Comment by pranav** [comment]
Thoughts on the background change @wylieconlon @ali ?

**Comment by wylieconlon** [comment]
Works for me

**Comment by pranav** [comment]
Making it live!

**Pull request merged**
